### ISSUE TITLE
Build fail with current mapnik-9999

### ISSUE THREAD

**Issue by wmyrda** [openstreetmap/mod_tile#164]
**gen_tile_test.cpp** has following code. 

```
#include <mapnik/version.hpp>
#if MAPNIK_VERSION < 200000
#include <mapnik/envelope.hpp>
#define image_32 Image32
#define image_data_32 ImageData32
#define box2d Envelope
#define zoom_to_box zoomToBox
#else
#include <mapnik/box2d.hpp>
#endif
```
Presently mapnik (git master as of July 1, 2017) does not install in include dir <mapnik/box2d.hpp> as it is not available anymore see https://github.com/mapnik/mapnik/tree/master/include/mapnik and it fails to build

**actual erorr**
```
/bin/sh ./libtool  --tag=CXX   --mode=link x86_64-pc-linux-gnu-g++  -march=native -O2 -pipe -fgcse-sm -fgcse-las -fgcse-after-reload -ftree-vectorize -fabi-version=0  -Wl,-O1 -Wl,--hash-style=both -Wl,--as-needed -Wl,--relax -Wl,--sort-common -o render_speedtest src/speedtest.o src/protocol_helper.o src/render_submit_queue.o src/sys_utils.o -pthread -liniparser -lm 
libtool: link: x86_64-pc-linux-gnu-g++ -march=native -O2 -pipe -fgcse-sm -fgcse-las -fgcse-after-reload -ftree-vectorize -fabi-version=0 -Wl,-O1 -Wl,--hash-style=both -Wl,--relax -Wl,--sort-common -o render_speedtest src/speedtest.o src/protocol_helper.o src/render_submit_queue.o src/sys_utils.o -pthread  -Wl,--as-needed -liniparser -lm -pthread
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I./includes  -pthread -DSYSTEM_LIBINIPARSER=1   -march=native -O2 -pipe -fgcse-sm -fgcse-las -fgcse-after-reload -ftree-vectorize -c -o src/render_old.o src/render_old.c
/bin/sh ./libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc  -march=native -O2 -pipe -fgcse-sm -fgcse-las -fgcse-after-reload -ftree-vectorize  -Wl,-O1 -Wl,--hash-style=both -Wl,--as-needed -Wl,--relax -Wl,--sort-common -o render_old src/store_file_utils.o src/render_old.o src/sys_utils.o src/protocol_helper.o src/render_submit_queue.o -pthread -liniparser -lm 
libtool: link: x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -fgcse-sm -fgcse-las -fgcse-after-reload -ftree-vectorize -Wl,-O1 -Wl,--hash-style=both -Wl,--relax -Wl,--sort-common -o render_old src/store_file_utils.o src/render_old.o src/sys_utils.o src/protocol_helper.o src/render_submit_queue.o -pthread  -Wl,--as-needed -liniparser -lm -pthread
x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I./includes  -pthread -DSYSTEM_LIBINIPARSER=1  -I/usr/include -I/usr/include/mapnik/agg -I/usr/include/mapnik -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/gdal -I/usr/include/postgresql-9.6 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DHAVE_LIBXML2 -std=c++14 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -march=native -pipe -O3 -ftree-vectorize -findirect-inlining -march=native -O2 -pipe -fgcse-sm -fgcse-las -fgcse-after-reload -ftree-vectorize -fabi-version=0 -c -o src/gen_tile_test-gen_tile_test.o `test -f 'src/gen_tile_test.cpp' || echo './'`src/gen_tile_test.cpp
src/gen_tile_test.cpp:58:28: fatal error: mapnik/box2d.hpp: Nie ma takiego pliku ani katalogu
 #include <mapnik/box2d.hpp>
                            ^
compilation terminated.
make[1]: *** [Makefile:1083: src/gen_tile_test-gen_tile_test.o] Błąd 1
make[1]: Opuszczenie katalogu '/tmp/portage/www-apache/mod_tile-9999/work/mod_tile-9999'
make: *** [Makefile:1299: all-recursive] Błąd 1
 * ERROR: www-apache/mod_tile-9999::gentoo-osm failed (compile phase):
 *   make failed
```
I would appreciate the fix for it.

**Comment by wmyrda** [comment]
I created following patch to mod_tile which made it compile against current mapnik, but renderd segfaults at the start :(

diff -Naur mod_tile-9999.old/src/gen_tile_test.cpp mod_tile-9999/src/gen_tile_test.cpp
--- mod_tile-9999.old/src/gen_tile_test.cpp     2017-07-02 15:44:05.640754137 +0200
+++ mod_tile-9999/src/gen_tile_test.cpp 2017-07-02 15:52:49.516055749 +0200
@@ -48,17 +48,20 @@
 #endif
 
 #include <mapnik/version.hpp>
-#if MAPNIK_VERSION < 200000
-#include <mapnik/envelope.hpp>
-#define image_32 Image32
-#define image_data_32 ImageData32
-#define box2d Envelope
-#define zoom_to_box zoomToBox
+#if MAPNIK_VERSION >= 300100
+   #include <mapnik/geometry/box2d.hpp>
 #else
-#include <mapnik/box2d.hpp>
+   #if MAPNIK_VERSION < 200000
+      #include <mapnik/envelope.hpp>
+      #define image_32 Image32
+      #define image_data_32 ImageData32
+      #define box2d Envelope
+      #define zoom_to_box zoomToBox
+   #else
+     #include <mapnik/box2d.hpp>
+   #endif
 #endif
 
-
 #define NO_QUEUE_REQUESTS 9
 #define NO_TEST_REPEATS 100
 #define NO_THREADS 100

**Comment by han-so1omon** [comment]
this still exists and the patch still works

**Comment by xamanu** [comment]
Thanks for the patch, I put it in a PR here: https://github.com/openstreetmap/mod_tile/pull/225 Please give it a round of testing, thanks.

**Comment by xamanu** [comment]
Tested it. While I can compile well with Mapnik 3.1.0 (under Debian Bullseye) it breaks when applying the patch:

```
src/gen_tile_test.cpp:46:10: fatal error: mapnik/geometry/box2d.hpp: No such file or directory
   46 | #include <mapnik/geometry/box2d.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by xamanu** [comment]
Please reopen (this or a new issue) if this is still a problem.
