### ISSUE TITLE
Compile errors on FreeBSD 10.1-RELEASE

### ISSUE THREAD

**Issue by lungdart** [openstreetmap/mod_tile#114]
mod_tile fails to compile out of the box on FreeBSD 10.1-RELEASE

1) The Makefile doesn't add /usr/local/include when compiling src/store_ro_http_proxy.c which causes curl/curl.h not to be found on the system. I'm not sure of the proper way to fix this, I just added it to AM_CPPFLAGS variable in Makefile.am before running autogen.sh and configure.

2) src/gen_tile_test.cpp needs to include sys/wait.h which contains some macros that are normally defined in stdlib.h on linux systems

3) src/gen_tile_test.cpp uses syscall(SYS_gettid); as a seed generator in function addition_thread (Around line 100). SYS_gettid is not suppored in FreeBSD, and the temporary solution I had was to include pthread.h and use (unsigned long long int)pthread_self(); instead. I don't believe this is ideal either. A good seed source should be found.

4) src/mod_tile.c uses ip.s6_addr32 which is not compatible with FreeBSD and OSX. This was noted before and patched to use the BSD friendly versions, but then changed back in https://github.com/openstreetmap/mod_tile/commit/8307d19ab7040691b1fd243052b6668a14f4df1f by reverting the hastag variable to it's previous iteration fixes this compiling error.

With these four changes I was able to get mod_tile to compile and install. There might be some consideration required to check if the system is FreeBSD and apply these changes? Sorry, not very familiar with the OSS scene, and git reporting.

Thanks!

**Comment by leforestier** [comment]
Hi, I have the same problem (trying to compile on FreeBSD 10.2-RELEASE).

I could go past step 1) by doing this.

    $ ./configure CFLAGS="-I/usr/local/include"
    $ make CFLAGS="-I/usr/local/include"

However I didn't know how to fix the other problems. The next one I got was:

    src/gen_tile_test.cpp:101:33: error: use of undeclared identifier 'SYS_gettid'
        unsigned int seed = syscall(SYS_gettid);
                                    ^
    src/gen_tile_test.cpp:588:17: error: use of undeclared identifier 'WEXITSTATUS'
              ret = WEXITSTATUS(ret);
                    ^
    src/gen_tile_test.cpp:595:17: error: use of undeclared identifier 'WEXITSTATUS'
              ret = WEXITSTATUS(ret);
                    ^
    src/gen_tile_test.cpp:602:17: error: use of undeclared identifier 'WEXITSTATUS'
              ret = WEXITSTATUS(ret);
                    ^
    4 errors generated.

If you managed to correct all the errors, maybe you could create a fork with your changes?
And maybe make a pull request?
I'd find it very useful.

**Comment by lungdart** [comment]
I honestly have no idea how to do that. (I'm a hardware guy, not familiar with collaboration tools and procedures.)

Here are the change sets though:

* src/gen_tile_test.cpp, Add the following includes
```cpp
#include <pthread.h>
#include <sys/wait.h>
```

* src/gen_tile_test.cpp, change *addition_thread() to look like this:
```cpp
void *addition_thread(void * arg) {
    struct request_queue * queue = (struct request_queue *)arg;
    struct item * item;
    struct timespec time;
    //unsigned int seed = syscall(SYS_gettid);
    unsigned int seed = (unsigned long long int)pthread_self();
    #ifdef __MACH__ // OS X does not have clock_gettime, use clock_get_time
```

* src/mod_tile.c Change the hashkey line to look like this
```cpp
//hashkey = (ip.s6_addr32[0] ^ ip.s6_addr32[1] ^ ip.s6_addr32[2] ^ ip.s6_addr32[3]) % DELAY_HASHTABLE_SIZ
hashkey = (*((uint32_t *)(&ip.s6_addr[0])) ^ *((uint32_t *)(&ip.s6_addr[4])) ^ *((uint32_t *)(&ip.s6_addr[8])) ^ *((uint32_t *)(&ip.s6_addr[12]))) % DELAY_HASHTABLE_SIZE;
```

Then it should compile. Feel free to turn these change sets into a patch to put upstream. Good luck!

**Comment by leforestier** [comment]
Thanks!
In the meantime I had managed to compile it by making similar changes (thanks to your first post).
I'll create a fork with the changes in the next few days..

**Comment by xamanu** [comment]
Related to #231
