### ISSUE TITLE
Can't build on Ubuntu 14.04

### ISSUE THREAD

**Issue by emilheunecke** [openstreetmap/mod_tile#233]
Hi, just a heads up, I'd been able to build an old Ubuntu 14.04 Dockerfile that uses mod_until until [this](https://github.com/openstreetmap/mod_tile/commit/8833bba9a2c2353d18816bd9d6c0917c64149595) recent commit, after which I get an error:

```
#18 8.225 config.status: executing libtool commands
#18 8.305 depbase=`echo src/daemon.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
#18 8.305       gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I./includes  -pthread   -g -O2 -MT src/daemon.o -MD -MP -MF $depbase.Tpo -c -o src/daemon.o src/daemon.c &&\
#18 8.305       mv -f $depbase.Tpo $depbase.Po
#18 8.330 src/daemon.c:47:33: fatal error: iniparser/iniparser.h: No such file or directory
#18 8.330  #include <iniparser/iniparser.h>
#18 8.330                                  ^
#18 8.330 compilation terminated.
#18 8.387 make: *** [src/daemon.o] Error 1
```

Not a significant issue, but just thought I'd share.

**Comment by xamanu** [comment]
Please use [version 0.5 of `mod_tile`](https://github.com/openstreetmap/mod_tile/releases/tag/0.5) for Ubuntu versions prior to 18.04 Bionic Beaver. `master` is to keep up with recent versions and is going to be even [included in the next Ubuntu release 21.04](https://packages.ubuntu.com/hirsute/renderd) - no need to compile anymore.
